code --install-extension althack.ament-task-provider --force &
code --install-extension bierner.markdown-mermaid --force &
code --install-extension DavidAnson.vscode-markdownlint --force &
code --install-extension Guyutongxue.cpp-reference --force &
code --install-extension janisdd.vscode-edit-csv --force &
code --install-extension jebbs.plantuml --force &
code --install-extension mechatroner.rainbow-csv --force &
code --install-extension ms-azuretools.vscode-docker --force &
code --install-extension ms-iot.vscode-ros --force &
code --install-extension ms-python.isort --force &
code --install-extension ms-python.python --force &
code --install-extension ms-python.vscode-pylance --force &
code --install-extension ms-toolsai.jupyter --force &
code --install-extension ms-toolsai.jupyter-keymap --force &
code --install-extension ms-toolsai.jupyter-renderers --force &
code --install-extension ms-toolsai.vscode-jupyter-cell-tags --force &
code --install-extension ms-toolsai.vscode-jupyter-slideshow --force &
code --install-extension ms-vscode.cmake-tools --force &
code --install-extension ms-vscode.cpptools --force &
code --install-extension ms-vscode.makefile-tools --force &
code --install-extension nonanonno.vscode-ros2 --force &
code --install-extension redhat.vscode-xml --force &
code --install-extension rust-lang.rust-analyzer --force &
code --install-extension slevesque.vscode-3dviewer --force &
code --install-extension streetsidesoftware.code-spell-checker --force &
code --install-extension tamasfe.even-better-toml --force &
code --install-extension twxs.cmake --force &
code --install-extension well-ar.plantuml --force
